services:
  - type: web
    name: flask-poetry
    runtime: image
    plan: starter
    autoDeploy: false
    image:
      url: robdimarcorender/mysql-example
      creds: 
        fromRegistryCreds:
          name: docker
